In [1]:
import nibabel
from nilearn import plotting
import os
import numpy as np
import pandas as pd
import scipy as sp

In [2]:
os.chdir('C:\Users\John\Documents\Code\\Python\\nsaba\\data_dir')

In [3]:
db_table = pd.read_table('database.txt')
feat_table = pd.read_table('features.txt')
expres_aba = pd.read_csv('MicroArrayExpression.csv')
annot_aba = pd.read_csv('SampleAnnot.csv')
probes_aba = pd.read_csv('Probes.csv')

In [4]:
print feat_table.shape
print db_table.shape

(10903, 3407)
(386455, 13)


In [7]:
mni_coords

array([[-10.1,   5.9,  -8.4],
       [  8.9,   8.5,  -7.4],
       [  7.9,   0.8,  -6.7],
       ..., 
       [ 26. , -15.4,  -8.8],
       [ 27.2, -15.4,  -8.8],
       [ 26. , -15.4,  -9.9]])

In [16]:
#KDTree for efficient MNI Coordinate Extraction
mni_coords = annot_aba.as_matrix()[1:, 10:].astype(float)
coord_tree = sp.spatial.KDTree(mni_coords)

i = coord_tree.query_ball_point([26,-15,-9], 2.0)
print coord_tree.data[i]


[[ 26.  -15.4  -8.8]
 [ 27.2 -15.4  -8.8]
 [ 26.  -15.4  -9.9]]


[889L, 890L, 891L]

In [6]:
# Get only MNI Coordinates
dbmni = db_table[db_table.space == 'MNI']

pmid 
 001 
 01 
 05 
 05 corrected 
 10 
 10 healthy 
 100 
 11 
 12 
 ... 
 years 
 years old 
 yield 
 yielded 
 young 
 young adults 
 young healthy 
 younger 
 younger adults 
 zone 
 
 
 
 
 0 
 9106283 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 1 
 9177231 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 2 
 9185551 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 3 
 9256495 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.110768 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 4 
 9288642 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 5 
 9395845 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 6 
 9405692 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 7 
 9408106 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.075810 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 8 
 9412517 
 0 
 0.000000 
 0.00000 
 0 
 0.086524 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 9 
 9465007 
 0 
 0.000000 
 0.00000 
 0 
 0.095763 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 10 
 9491989 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 11 
 9501235 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 12 
 9593960 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.114793 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 13 
 9620697 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.109740 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 14 
 9620698 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 15 
 9620699 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 16 
 9636217 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 17 
 9714705 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 18 
 9728909 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 19 
 9770542 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 20 
 9787003 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0 
 0.000000 
 0.00000 
 0 
 
 
 21 
 9808463 
 0 
 0.000000 
 0.00000 
 0 
 0.000000 
 0 
 0 
 0 
 0.000000 
 ... 
 0.000000 
 0 
 0.000000 
 0.00000