In [1]:
import nibabel
from nilearn import plotting
import os
import numpy as np
import pandas as pd
import scipy as sp
import random as rn

In [2]:
os.chdir('C:\Users\John\Documents\Code\\Python\\nsaba\\data_dir')

In [3]:
db_table = pd.read_table('database.txt')
feat_table = pd.read_table('features.txt')
expres_aba = pd.read_csv('MicroArrayExpression.csv')
annot_aba = pd.read_csv('SampleAnnot.csv')
probes_aba = pd.read_csv('Probes.csv')

In [4]:
print feat_table.shape
print db_table.shape

(10903, 3407)
(386455, 13)


In [7]:
mni_coords

array([[-10.1,   5.9,  -8.4],
       [  8.9,   8.5,  -7.4],
       [  7.9,   0.8,  -6.7],
       ..., 
       [ 26. , -15.4,  -8.8],
       [ 27.2, -15.4,  -8.8],
       [ 26. , -15.4,  -9.9]])

In [260]:
#KDTree for efficient MNI Coordinate Extraction
mni_coords = annot_aba.as_matrix()[1:, 10:].astype(float)
coord_tree = sp.spatial.KDTree(mni_coords)

pts = [rn.u]
i = coord_tree.query_ball_point([26,-15,-9], 5.0)
print coord_tree.data[i]


[[ 26.  -15.4  -8.8]
 [ 27.2 -15.4  -8.8]
 [ 26.  -15.4  -9.9]
 [ 26.  -16.4  -6.3]]


In [6]:
# Get only MNI Coordinates
dbmni = db_table[db_table.space == 'MNI']

In [229]:
annot_aba.loc[:,'mni_x':'mni_z'].as_matrix()

array([[-29.2,   5.8,  -2.6],
       [-10.1,   5.9,  -8.4],
       [  8.9,   8.5,  -7.4],
       ..., 
       [ 26. , -15.4,  -8.8],
       [ 27.2, -15.4,  -8.8],
       [ 26. , -15.4,  -9.9]])

In [231]:
db_table = db_table.loc[db_table.space == 'MNI', ['id','x','y','z']]

In [135]:
# ID to terms
ID = 9185551
df = feat_table.loc[feat_table['pmid'] == ID, feat_table.loc[feat_table['pmid'] == ID].iloc[0] > 0]
df

pmid  accounted  anterior  anterior temporal  bilaterally     blood  \
2  9185551   0.126286   0.04888           0.112669     0.083018  0.077009   

   blood flow   central  cerebral  cerebral blood       ...        \
2    0.111414  0.081773  0.152437        0.113549       ...         

   stimulation  structures   suggest  temporal  temporal lobe  thresholds  \
2     0.079183      0.0764  0.046337  0.179396       0.253363     0.39559   

   tomography  treatment     using     water  
2    0.098813   0.092124  0.040626  0.131512  

[1 rows x 63 columns]

In [255]:
# Term to IDs

term = ''
term_ids_act = feat_table.loc[feat_table[term] > 0, ['pmid', term]]
term_ids = term_ids_act['pmid'].tolist()
term_ids.
term_ids_act

pmid      bold
8       9412517  0.039470
32     10197540  0.072965
75     10643727  0.426579
118    10869575  0.070514
157    11126640  0.035764
167    11167053  0.064741
184    11239901  0.048715
190    11257281  0.119811
206    11335694  0.104488
219    11463481  0.043021
237    11578663  0.060141
247    11595391  0.166657
255    11689304  0.082272
261    11704079  0.037855
276    11835600  0.060255
307    11958958  0.064313
313    12003859  0.076791
318    12050089  0.039266
358    12193197  0.059787
372    12356445  0.065407
377    12372290  0.081237
386    12397138  0.084080
387    12399015  0.105628
425    12507947  0.052103
429    12518293  0.299611
445    12574477  0.036823
459    12595190  0.091985
469    12599275  0.055650
486    12644355  0.079935
497    12667851  0.054472
...         ...       ...
10548  25161897  0.147684
10560  25173413  0.055277
10580  25204866  0.039554
10583  25205663  0.183371
10586  25208743  0.240724
10619  25255048  0.096786
10638  25279457  0.064931
10640  25281280  0.212876
10641  25281799  0.045027
10666  25312831  0.162180
10680  25337918  0.051626
10692  25379416  0.218617
10699  25379440  0.097285
10700  25379447  0.064902
10708  25414630  0.058215
10717  25439393  0.042748
10722  25444600  0.189113
10745  25451474  0.050051
10746  25451479  0.168388
10756  25459293  0.120007
10760  25461267  0.187249
10761  25461703  0.076036
10762  25461704  0.226378
10787  25471589  0.128540
10798  25487911  0.054332
10834  25528288  0.060510
10858  25568119  0.053439
10884  25610763  0.061863
10888  25610783  0.073609
10890  25613405  0.046401

[966 rows x 2 columns]

In [258]:
# IDs to Coords
term_coords = db_table.loc[db_table['id'].isin(term_ids)]
tc = term_coords.as_matrix().astype(float)
term_coords



id   x   y   z
3129    10869575  21  23  25
3130    10869575   1   3   5
4178    11167053  38 -54 -36
4179    11167053 -10 -78 -36
4180    11167053 -34 -48 -36
4181    11167053 -16 -28 -36
4182    11167053  24 -32 -32
4183    11167053   4  -8   8
4184    11167053  20  -6  12
4185    11167053 -34  -4   0
4186    11167053  -6  -4   8
4187    11167053 -18 -10  12
4188    11167053  -4  30  44
4189    11167053  36  18  44
4190    11167053 -38  26  44
4191    11167053 -42  10  44
4192    11167053  44   0 -16
4193    11167053  12 -60   4
4194    11167053  46 -72  28
4195    11167053 -12 -56  48
4196    11167053 -20 -60 -44
4197    11167053 -16 -82 -44
4198    11167053 -46 -56 -44
4199    11167053  22 -64 -44
4200    11167053  16 -82 -32
4201    11167053  40 -58 -40
4202    11167053  -2 -18   4
4203    11167053 -20  10  -4
4204    11167053  40  38  36
4205    11167053  12  36  28
...          ...  ..  ..  ..
385230  25568119  36   3  42
385231  25568119  30  49  18
385232  25568119  37  12  38
385233  25568119  38 -56  42
385234  25568119  42  31   3
385235  25568119 -27 -66 -31
385236  25568119 -36 -62 -24
385237  25568119 -37  54 -37
385238  25568119  29 -60 -32
385239  25568119  25 -73 -32
385240  25568119  15 -69 -28
385241  25568119  27 -14   8
385242  25568119  25  -5  -1
385243  25568119 -27 -18   8
385244  25568119 -28  -5   2
385245  25568119  38  44   9
385246  25568119   0 -28  58
386076  25613405 -24 -66  48
386077  25613405 -32 -88  22
386078  25613405 -40 -40  50
386079  25613405 -32 -56 -14
386080  25613405 -44 -76  -8
386081  25613405  22 -88 -16
386082  25613405  44  -2  50
386083  25613405 -24  -8  54
386084  25613405 -28 -86  -8
386085  25613405  22 -64  58
386086  25613405  34 -56  54
386087  25613405  46 -62  10
386088  25613405  -6 -74 -23

[24400 rows x 4 columns]

In [241]:
feat_table

pmid  001        01       05  05 corrected        10  10 healthy  \
0       9106283    0  0.000000  0.00000             0  0.000000           0   
1       9177231    0  0.000000  0.00000             0  0.000000           0   
2       9185551    0  0.000000  0.00000             0  0.000000           0   
3       9256495    0  0.000000  0.00000             0  0.000000           0   
4       9288642    0  0.000000  0.00000             0  0.000000           0   
5       9395845    0  0.000000  0.00000             0  0.000000           0   
6       9405692    0  0.000000  0.00000             0  0.000000           0   
7       9408106    0  0.000000  0.00000             0  0.000000           0   
8       9412517    0  0.000000  0.00000             0  0.086524           0   
9       9465007    0  0.000000  0.00000             0  0.095763           0   
10      9491989    0  0.000000  0.00000             0  0.000000           0   
11      9501235    0  0.000000  0.00000             0  0.000000           0   
12      9593960    0  0.000000  0.00000             0  0.000000           0   
13      9620697    0  0.000000  0.00000             0  0.000000           0   
14      9620698    0  0.000000  0.00000             0  0.000000           0   
15      9620699    0  0.000000  0.00000             0  0.000000           0   
16      9636217    0  0.000000  0.00000             0  0.000000           0   
17      9714705    0  0.000000  0.00000             0  0.000000           0   
18      9728909    0  0.000000  0.00000             0  0.000000           0   
19      9770542    0  0.000000  0.00000             0  0.000000           0   
20      9787003    0  0.000000  0.00000             0  0.000000           0   
21      9808463    0  0.000000  0.00000             0  0.000000           0   
22      9838166    0  0.000000  0.00000             0  0.000000           0   
23      9886448    0  0.000000  0.00000             0  0.000000           0   
24      9988836    0  0.000000  0.00000             0  0.000000           0   
25      9990082    0  0.000000  0.00000             0  0.000000           0   
26     10022492    0  0.000000  0.00000             0  0.000000           0   
27     10022494    0  0.000000  0.00000             0  0.000000           0   
28     10022496    0  0.000000  0.00000             0  0.000000           0   
29     10051677    0  0.000000  0.00000             0  0.000000           0   
...         ...  ...       ...      ...           ...       ...         ...   
10873  25592803    0  0.000000  0.00000             0  0.000000           0   
10874  25592995    0  0.000000  0.00000             0  0.000000           0   
10875  25592998    0  0.000000  0.00000             0  0.000000           0   
10876  25595179    0  0.000000  0.00000             0  0.000000           0   
10877  25595222    0  0.000000  0.00000             0  0.000000           0   
10878  25595501    0  0.000000  0.00000             0  0.000000           0   
10879  25596443    0  0.153638  0.00000             0  0.000000           0   
10880  25596444    0  0.000000  0.00000             0  0.000000           0   
10881  25598049    0  0.000000  0.00000             0  0.000000           0   
10882  25601007    0  0.000000  0.00000             0  0.000000           0   
10883  25609637    0  0.000000  0.06648             0  0.000000           0   
10884  25610763    0  0.000000  0.00000             0  0.000000           0   
10885  25610767    0  0.000000  0.00000             0  0.000000           0   
10886  25610773    0  0.000000  0.00000             0  0.000000           0   
10887  25610777    0  0.000000  0.00000             0  0.000000           0   
10888  25610783    0  0.000000  0.00000             0  0.000000           0   
10889  25610794    0  0.000000  0.00000             0  0.000000           0   
10890  25613405    0  0.000000  0.00000             0  0.000000           0   
10891  25613438    0  0.000000  0.00000             0  0.0000