# Testing Nsaba Functionality

##### Current Methods
- get_aba_ge()
- get_ns_act()
- make_ge_ns_mat()
- coords_to_ge()

In [3]:
%pylab inline
from nsaba.nsaba import Nsaba
import numpy as np
import os
import matplotlib.pyplot as plt
import pandas as pd
import itertools

Populating the interactive namespace from numpy and matplotlib


In [1]:
%load_ext line_profiler

In [4]:
# Simon Path IO

data_dir = 'C:\Users\\John\\Documents\\Code\\Python\\nsaba\\data_dir'
os.chdir(data_dir)
Nsaba.aba_load()
Nsaba.ns_load()

This may take a minute or two ...
SampleAnnot.csv loaded.
MicroarrayExpression.csv loaded.
Probes.csv loaded.
Nsaba.aba['mni_coords'] initialized.
database.txt loaded.
features.txt loaded.
Nsaba.ns['mni_coords'] initialized.


0

In [2]:
#Torben Path IO

ns_path = "/Users/Torben/Documents/ABI analysis/current_data_new/"
aba_path = '/Users/Torben/Documents/ABI analysis/normalized_microarray_donor9861/'
#ns_path = '/Users/SP/Documents/'
#aba_path = '/Users/SP/Documents/'

Nsaba.aba_load(aba_path)
Nsaba.ns_load(ns_path)

This may take a minute or two ...
SampleAnnot.csv loaded.
MicroarrayExpression.csv loaded.
Probes.csv loaded.
Nsaba.aba['mni_coords'] initialized.
database.txt loaded.
features.txt loaded.
Nsaba.ns['mni_coords'] initialized.


0

In [5]:
# Loading gene expression for all ABA registered Entrez IDs.
A = Nsaba()
A.load_ge_pickle('Nsaba_ABA_ge.pkl')
%time A.get_ns_act('attention',thresh = -1)

'ge' dictionary successfully loaded
Wall time: 1min 27s


### Coordinates to gene expression:

Provide a list of coordinates and entrez_ids and the function will return matrix of coordinates by gene expression

In [20]:
rand = lambda null: np.random.uniform(-10,10,3).tolist()
coord_num = 20
coords = [rand(0) for i in range(coord_num)]

A.coords_to_ge(coords, entrez_ids=[733,88,33], search_radii=8)

array([[  2.95252348,   6.03561137,   2.69794285],
       [  3.52519708,   6.458542  ,   2.4030091 ],
       [  2.84469617,   7.89788825,   3.99618469],
       [  2.99453096,   7.1353023 ,   2.9386428 ],
       [  3.4826444 ,   6.66018503,   2.58705114],
       [  2.96720005,  10.3898135 ,   2.89236149],
       [  2.90893164,   8.40273253,   3.87202044],
       [  2.85349948,   9.2817149 ,   2.48898334],
       [  3.73756151,   7.13741913,   2.47894927],
       [  3.25248937,   6.85801368,   2.98475387],
       [  3.14981697,   6.78971634,   2.66228961],
       [  2.51228372,   7.47008172,   3.6751625 ],
       [  3.54085305,   7.90193468,   4.38219196],
       [  3.37034544,   7.0325413 ,   3.06462396],
       [  3.27035588,   9.07505534,   3.67968551],
       [  3.08111389,   6.55549416,   2.57867783],
       [  2.89267203,   9.68816812,   2.50871988],
       [  2.74803579,   9.39299141,   2.34289985],
       [  3.0203406 ,   5.88909839,   2.77142903],
       [  3.20993856,  10.41934

In [22]:
A.get_ns_act("attention", thresh=.35, method='knn')

# You can use the sphere method too, if you want to weight by bucket. 
# e.g:
# A.get_ns_act("attention", thresh=.3, method='sphere')

A.make_ge_ns_mat('attention', [733, 33, 88])

array([[  2.67576294,   3.55524357,   9.52009698,   0.4299227 ],
       [  3.16345034,   3.09866393,   7.60823895,   0.42182709],
       [  3.50634313,   2.99317391,   8.29352977,   0.36385783],
       [  3.29699796,   2.78437501,   7.93032253,   0.36385783],
       [  2.61963057,   3.77371768,   7.19261796,   0.36327587],
       [  1.96681394,   3.65214963,   8.92154224,   0.36327587],
       [  3.98321459,   3.4525211 ,   9.06477708,   0.37779626],
       [  4.07375417,   3.40767968,   9.34995374,   0.44083295],
       [  3.83224791,   3.23951905,   9.28899256,   0.41226568],
       [  3.67989062,   3.30211262,   9.08570592,   0.42658221],
       [  3.66007911,   3.96197038,   9.29246256,   0.43338531],
       [  3.92544649,   3.41030426,   9.22098115,   0.41338453],
       [  3.76139132,   2.82685937,   8.87648191,   0.37779626],
       [  3.96556067,   3.24690584,   8.74796376,   0.41226568],
       [  3.90611693,   3.61686791,   8.9889376 ,   0.43338531],
       [  3.3004406 ,   2

In [21]:
A.make_ge_ns_mat('spatial', [733, 33, 88])

Either term['spatial'] or one or more Entrez ID keys does not exist; please check arguments


## Visualization Methods (testing)

In [7]:
def visualize_ns(term, points=200):
        if term in A.term:
            term_index = A.ns['features_df'].columns.get_loc(term)
            import matplotlib.pyplot as plt
            import matplotlib.cm as cm
            from mpl_toolkits.mplot3d import Axes3D
            rand_point_inds = np.random.random_integers(0, len(np.squeeze(zip(A.ns['mni_coords'].data))), points)
            rand_points = np.squeeze(zip(A.ns['mni_coords'].data))[rand_point_inds]
            weights = []
            inds_of_real_points_with_no_fucking_missing_study_ids = []
            for rand_point in range(len(rand_points)):
                if len(A.coord_to_terms(rand_points[rand_point].astype(list))) > 0:
                    print 'good point' + str(rand_points[rand_point])
                    inds_of_real_points_with_no_fucking_missing_study_ids.append(rand_point_inds[rand_point])
                    weights.append(A.coord_to_terms(rand_points[rand_point].astype(list))[term_index])
                else:
                    print 'bad point ' + str(rand_points[rand_point])
            fig = plt.figure()
            ax = fig.add_subplot(111, projection='3d')
            colors = cm.jet(weights/max(weights))
            color_map = cm.ScalarMappable(cmap=cm.jet)
            color_map.set_array(weights)
            fig.colorbar(color_map)
            x = A.ns['mni_coords'].data[inds_of_real_points_with_no_fucking_missing_study_ids, 0]
            y = A.ns['mni_coords'].data[inds_of_real_points_with_no_fucking_missing_study_ids, 1]
            z = A.ns['mni_coords'].data[inds_of_real_points_with_no_fucking_missing_study_ids, 2]
        else:
            print 'Term '+term + ' has not been initialized. Use self.get_ns_act(' + term + ',thresh = 0.01)'
        ax.scatter(x, y, z, c=colors, alpha=0.4)
        ax.set_title('Estimation of ' + term)

        return fig
    
visualize_ns('attention')

[  9.  45. -18.]
[-26. -50.  -4.]
[ 52.  15.  24.]
[-54.  16.  18.]
[-12.   9.  66.]
[-42. -66.  -5.]
[ 39.  -9.  27.]
[-36.  -8. -10.]
[ 33. -75.  -3.]
[-52.   4. -34.]
[ 41.  36.  23.]
[-54.  15.  12.]
[-66. -14.   8.]
[  8.  -7.  21.]
[-62. -18.  -4.]
[ 10.  54.  20.]
[-55.2  -2.   31. ]
[ 70.   0.  24.]
[ 12.  16.  34.]
[ 28.  -4.   8.]
[-16. -10. -15.]
[ 57.  30.   0.]
[-26.  16.   2.]
[ 14. -68.   3.]
[ 55.   4.  13.]
[-42.  -8.  14.]
[ 22. -84.  -4.]
[ 28. -13.  -8.]
[ 56.   8.  34.]
[-8.  2.  4.]
[ 14. -12.  54.]
[  6. -51.  51.]
[-49.  22.  22.]
[ 32. -33.  -8.]
[ 31.  25.  -5.]
[ 51.  15.  12.]
[ 27.   8.  55.]
[-30. -60.  52.]
[ 44.  20.   7.]
[ 24. -12.   2.]
[  8.  16.  28.]
[ -4.  24.  62.]
[-45. -57.  27.]
[ 33.  29.  43.]
[-30. -81. -36.]
[ 45.  11.  -7.]
[ 22.  12.  -2.]
[ 34. -48.  58.]
[-34.  56.   6.]
[-20. -60.   8.]
[-50. -16.  50.]
[  0.  21.  44.]
[-46. -68.   2.]
[-43. -39.  30.]
[-38. -56.  54.]
[ 58. -16.  10.]
[ -9. -15.   9.]
[ -4. -76. -12.]
[  0.  22.  52

KeyboardInterrupt: 